language: node_js
node_js:
- 5.11.1
script:
- make test
before_script:
- npm install --only=dev
before_deploy:
  script: make deploy-assets-staging
deploy:
  provider: heroku
  on: develop
  api_key:
    secure: jZIwuTvmr1Ez4eClIPKILBicnQpVRwrRmr2z9jvLgpOA7a225JZct8S+Dpe/4caLVAQCLr9DNFSnyI0ZhoheCxyeHKmOJ+bxzuPbmoufHJ+GcCGbEMfKNOTnf3uYPO/TWZKb/2JKzfpQo/85NQ8ykNdOe87eIcLNBqW9a5RQbFw=
  app:
    develop: ervell-staging
env:
  global:
  - secure: WJGcHqZmm2PTFcuyT9HMcJYp2Oosb9VCyZxAQ56Y/PAChM6uhvWryJlTQdaOymXpbOHLXv0X3zE3tbmJhH7i1f2cgQpXV9fzgqx35zGxVcgGLWMSerEw77828/ZBVlhbhYX9o0gUel0Z3Rz4U5LOw4Uy4YgBQab3Q/W8Qf04vj4=
  - secure: D6goSBaFU2y6Ql56WYj6RE1XW5dbKUoZXEHBcVMIoZSgG9ejd/N7G4nBoo6bOoXzVQhYLPI2fINmkJeZVeYfpWxE84cLX2zPPiRixE8/xJzf68MGcB4x6YobN+n2zoOxRe9N1n0CmHt7kwKzYuCpoXMcYraL5PIi+8nzSx9Ppjo=
