language: node_js
node_js:
- '8'
script:
- make test
before_deploy:
- if [ $TRAVIS_BRANCH = 'master' ]; then APP_NAME=ervell-staging S3_BUCKET=ervell-staging yarn predeploy; fi
- if [ $TRAVIS_BRANCH = 'deploy' ]; then APP_NAME=ervell S3_BUCKET=ervell-production yarn predeploy; fi
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: jZIwuTvmr1Ez4eClIPKILBicnQpVRwrRmr2z9jvLgpOA7a225JZct8S+Dpe/4caLVAQCLr9DNFSnyI0ZhoheCxyeHKmOJ+bxzuPbmoufHJ+GcCGbEMfKNOTnf3uYPO/TWZKb/2JKzfpQo/85NQ8ykNdOe87eIcLNBqW9a5RQbFw=
  app:
    master: ervell-staging
    deploy: ervell
env:
  global:
  - secure: WJGcHqZmm2PTFcuyT9HMcJYp2Oosb9VCyZxAQ56Y/PAChM6uhvWryJlTQdaOymXpbOHLXv0X3zE3tbmJhH7i1f2cgQpXV9fzgqx35zGxVcgGLWMSerEw77828/ZBVlhbhYX9o0gUel0Z3Rz4U5LOw4Uy4YgBQab3Q/W8Qf04vj4=
  - secure: D6goSBaFU2y6Ql56WYj6RE1XW5dbKUoZXEHBcVMIoZSgG9ejd/N7G4nBoo6bOoXzVQhYLPI2fINmkJeZVeYfpWxE84cLX2zPPiRixE8/xJzf68MGcB4x6YobN+n2zoOxRe9N1n0CmHt7kwKzYuCpoXMcYraL5PIi+8nzSx9Ppjo=
  - secure: gJ3Pwp07inioC4PiWddxTeMdbcMEDO/ecwTuVbUcos1nqC6qVQ0CK2ZEeDBkJhEoChREiJpIWoF0s8oRmupNZCCTpu5ow6gncbrErLHo3iD+ZUt+EVvLQ40+DMtZT2cdIGJJc+c1R3M2hZjT4X+irRHpFN/kMaKxi+G2WWVmLQo=
notifications:
  slack:
    secure: H3VQ6R1DXG6exptAbzUo93ia4JkkDWLmd7vQU60FM4pxyjhw9almd+K2GMR5QDMhqUP3Pb/m+pHOwhLWEVHTWhT5jqYW6IzwU0X0AHMK2q5pUtSCitL6I42YPpOGdd6kQzC5h/qpojoaTJgvFTIf4js8HeEYPImfzDV4AeDrQMs=
